import { config } from "dotenv";
import { resolve } from "path";
config({ path: resolve(process.cwd(), ".env.local") });

const MOCK_PROPERTIES = [
  {
    portal: "zonaprop",
    portalId: "zp-001",
    url: "https://www.zonaprop.com.ar/propiedades/departamento-en-alquiler-palermo-001.html",
    title: "Departamento 3 ambientes en Palermo",
    description: "Hermoso departamento con balcón, piso alto, luminoso. A metros de Av. Santa Fe. Cocina condesa, lavarropas, split frío/calor.",
    price: "850000",
    currency: "ARS",
    address: "Av. Santa Fe 3456, Piso 8",
    city: "Palermo",
    state: "Capital Federal",
    country: "AR",
    zip: "1425",
    lat: -34.5895,
    lng: -58.3825,
    bedrooms: 2,
    bathrooms: 1,
    area: "75",
    areaUnit: "m2",
    parkingSpaces: 1,
    furnished: false,
    petFriendly: true,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-01"),
    contentHash: "zp-001-hash",
    expenses: "95000",
  },
  {
    portal: "zonaprop",
    portalId: "zp-002",
    url: "https://www.zonaprop.com.ar/propiedades/departamento-en-alquiler-recoleta-002.html",
    title: "Departamento 2 ambientes en Recoleta",
    description: "Moderno departamento a estrenar. Cocina integral, estufa a gas, pisos de porcelanato. Cerca del Cementerio de la Recoleta.",
    price: "720000",
    currency: "ARS",
    address: "Juncal 1234, Piso 3",
    city: "Recoleta",
    state: "Capital Federal",
    country: "AR",
    zip: "1116",
    lat: -34.5868,
    lng: -58.3942,
    bedrooms: 1,
    bathrooms: 1,
    area: "55",
    areaUnit: "m2",
    parkingSpaces: 0,
    furnished: false,
    petFriendly: false,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-03"),
    contentHash: "zp-002-hash",
    expenses: "65000",
  },
  {
    portal: "zonaprop",
    portalId: "zp-003",
    url: "https://www.zonaprop.com.ar/propiedades/casa-en-venta-belgrano-003.html",
    title: "Casa quintas en Belgrano",
    description: "Casa quintas de 4 ambientes con jardín, parrilla y pileta. Barrio cerrado Los Robles. Seguridad 24hs.",
    price: "450000",
    currency: "USD",
    address: "Av. Virrey del Pino 2345",
    city: "Belgrano",
    state: "Capital Federal",
    country: "AR",
    zip: "1426",
    lat: -34.5612,
    lng: -58.4541,
    bedrooms: 3,
    bathrooms: 2,
    area: "180",
    areaUnit: "m2",
    parkingSpaces: 2,
    furnished: true,
    petFriendly: true,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-05-28"),
    contentHash: "zp-003-hash",
    expenses: "0",
  },
  {
    portal: "argenprop",
    portalId: "ap-001",
    url: "https://www.argenprop.com/departamento-en-alquiler-en-palermo--18000001",
    title: "Departamento 4 ambientes en Palermo Hollywood",
    description: "Amplio departamento con vista al parque Las Heras. Living comedor, cocina americana, 3 dormitorios con placard. Ideal familias.",
    price: "1200000",
    currency: "ARS",
    address: "Av. Dorrego 567, Piso 12",
    city: "Palermo",
    state: "Capital Federal",
    country: "AR",
    zip: "1414",
    lat: -34.5789,
    lng: -58.4298,
    bedrooms: 3,
    bathrooms: 2,
    area: "120",
    areaUnit: "m2",
    parkingSpaces: 1,
    furnished: false,
    petFriendly: true,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-02"),
    contentHash: "ap-001-hash",
    expenses: "150000",
  },
  {
    portal: "argenprop",
    portalId: "ap-002",
    url: "https://www.argenprop.com/departamento-en-alquiler-en-villa-crespo--18000002",
    title: "Departamento 2 ambientes en Villa Crespo",
    description: "Departamento con parquet, balconcito a la calle. Muy luminoso. A una cuadra del subte. Cocina renovada.",
    price: "580000",
    currency: "ARS",
    address: "Murillo 890, Piso 5",
    city: "Villa Crespo",
    state: "Capital Federal",
    country: "AR",
    zip: "1414",
    lat: -34.5978,
    lng: -58.4389,
    bedrooms: 1,
    bathrooms: 1,
    area: "48",
    areaUnit: "m2",
    parkingSpaces: 0,
    furnished: false,
    petFriendly: false,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-05"),
    contentHash: "ap-002-hash",
    expenses: "45000",
  },
  {
    portal: "argenprop",
    portalId: "ap-003",
    url: "https://www.argenprop.com/departamento-en-venta-en-nunez--18000003",
    title: "Departamento 3 ambientes en Nuñez",
    description: "Depto a estrenar en torre nueva. Gym, sum, cowork. Cochera cubierta. Excelente calidad de construcción.",
    price: "280000",
    currency: "USD",
    address: "Cabello 3456, Piso 15",
    city: "Nuñez",
    state: "Capital Federal",
    country: "AR",
    zip: "1428",
    lat: -34.5412,
    lng: -58.4498,
    bedrooms: 2,
    bathrooms: 2,
    area: "95",
    areaUnit: "m2",
    parkingSpaces: 1,
    furnished: false,
    petFriendly: true,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-04"),
    contentHash: "ap-003-hash",
    expenses: "0",
  },
  {
    portal: "zonaprop",
    portalId: "zp-004",
    url: "https://www.zonaprop.com.ar/propiedades/departamento-en-alquiler-san-telmo-004.html",
    title: "Departamento tipo PH en San Telmo",
    description: "PH con techo alto de 4 metros, piso de madera original. A 2 cuadras de la Plaza Dorrego. Ideal artistas.",
    price: "490000",
    currency: "ARS",
    address: "Defensa 1567",
    city: "San Telmo",
    state: "Capital Federal",
    country: "AR",
    zip: "1065",
    lat: -34.6245,
    lng: -58.3734,
    bedrooms: 1,
    bathrooms: 1,
    area: "42",
    areaUnit: "m2",
    parkingSpaces: 0,
    furnished: true,
    petFriendly: true,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-01"),
    contentHash: "zp-004-hash",
    expenses: "30000",
  },
  {
    portal: "zonaprop",
    portalId: "zp-005",
    url: "https://www.zonaprop.com.ar/propiedades/departamento-en-alquiler-caballito-005.html",
    title: "Departamento 3 ambientes en Caballito",
    description: "Departamento familiar en piso bajo. Jardín privado. A metros de la Av. Rivadavia y del Parque Rivadavia.",
    price: "680000",
    currency: "ARS",
    address: "Av. Rivadavia 5678, Piso 1",
    city: "Caballito",
    state: "Capital Federal",
    country: "AR",
    zip: "1424",
    lat: -34.6189,
    lng: -58.4432,
    bedrooms: 2,
    bathrooms: 1,
    area: "80",
    areaUnit: "m2",
    parkingSpaces: 1,
    furnished: false,
    petFriendly: true,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-03"),
    contentHash: "zp-005-hash",
    expenses: "70000",
  },
  {
    portal: "argenprop",
    portalId: "ap-004",
    url: "https://www.argenprop.com/casa-en-venta-en-martinez--18000004",
    title: "Casa en Martinez con jardín y pileta",
    description: "Casa de 5 ambientes en zona residencial. Jardín con parrilla, pileta, playroom. Cuarto de servicio. Alarmas.",
    price: "520000",
    currency: "USD",
    address: "Los Troncos 234",
    city: "Martinez",
    state: "Buenos Aires",
    country: "AR",
    zip: "1640",
    lat: -34.4891,
    lng: -58.5178,
    bedrooms: 4,
    bathrooms: 3,
    area: "320",
    areaUnit: "m2",
    parkingSpaces: 3,
    furnished: true,
    petFriendly: true,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-05-30"),
    contentHash: "ap-004-hash",
    expenses: "0",
  },
  {
    portal: "zonaprop",
    portalId: "zp-006",
    url: "https://www.zonaprop.com.ar/propiedades/departamento-en-alquiler-microcentro-006.html",
    title: "Departamento 1 ambiente en Microcentro",
    description: "Departamento funcional en pleno Microcentro. A pasos de la Obelisco. Ideal para profesionales. Todo nuevo.",
    price: "420000",
    currency: "ARS",
    address: "Av. Corrientes 1234, Piso 10",
    city: "Microcentro",
    state: "Capital Federal",
    country: "AR",
    zip: "1043",
    lat: -34.6034,
    lng: -58.3816,
    bedrooms: 1,
    bathrooms: 1,
    area: "35",
    areaUnit: "m2",
    parkingSpaces: 0,
    furnished: true,
    petFriendly: false,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-05"),
    contentHash: "zp-006-hash",
    expenses: "38000",
  },
  {
    portal: "argenprop",
    portalId: "ap-005",
    url: "https://www.argenprop.com/departamento-en-venta-en-palermo--18000005",
    title: "Departamento 2 ambientes en Palermo Soho",
    description: "Depto con encanto en zona gastronómica. Piso de madera, cocina abierta. Balcón con vista a la calle arbolada.",
    price: "195000",
    currency: "USD",
    address: "Costa Rica 4567, Piso 4",
    city: "Palermo",
    state: "Capital Federal",
    country: "AR",
    zip: "1414",
    lat: -34.5801,
    lng: -58.4234,
    bedrooms: 1,
    bathrooms: 1,
    area: "58",
    areaUnit: "m2",
    parkingSpaces: 0,
    furnished: false,
    petFriendly: true,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-02"),
    contentHash: "ap-005-hash",
    expenses: "0",
  },
  {
    portal: "zonaprop",
    portalId: "zp-007",
    url: "https://www.zonaprop.com.ar/propiedades/departamento-en-alquiler-flores-007.html",
    title: "Departamento 2 ambientes en Flores",
    description: "Departamento económico en Flores. Cerca del shopping. Transporte público accesible. Buenos vecinos.",
    price: "350000",
    currency: "ARS",
    address: "Av. Rivadavia 8901, Piso 2",
    city: "Flores",
    state: "Capital Federal",
    country: "AR",
    zip: "1406",
    lat: -34.6329,
    lng: -58.4691,
    bedrooms: 1,
    bathrooms: 1,
    area: "45",
    areaUnit: "m2",
    parkingSpaces: 0,
    furnished: false,
    petFriendly: false,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-04"),
    contentHash: "zp-007-hash",
    expenses: "25000",
  },
  {
    portal: "argenprop",
    portalId: "ap-006",
    url: "https://www.argenprop.com/ph-en-alquiler-en-san-telmo--18000006",
    title: "PH con patio en San Telmo",
    description: "PH entero con patio delantero y trasero. Cocina completa, lavarropas. Muy tranquilo. Ideal parejas.",
    price: "520000",
    currency: "ARS",
    address: "Balcarce 789",
    city: "San Telmo",
    state: "Capital Federal",
    country: "AR",
    zip: "1064",
    lat: -34.6267,
    lng: -58.3712,
    bedrooms: 2,
    bathrooms: 1,
    area: "65",
    areaUnit: "m2",
    parkingSpaces: 0,
    furnished: true,
    petFriendly: true,
    images: [],
    mainImage: null,
    publishedAt: new Date("2026-06-06"),
    contentHash: "ap-006-hash",
    expenses: "20000",
  },
];

async function main() {
  const { db } = await import("../src/lib/db");
  const { properties } = await import("../src/lib/schema");

  console.log("🌱 Seeding database with mock properties...");

  let inserted = 0;
  for (const prop of MOCK_PROPERTIES) {
    try {
      await db.insert(properties).values(prop).onConflictDoNothing();
      inserted++;
    } catch (e: any) {
      console.error(`Error inserting ${prop.portalId}:`, e.message);
    }
  }

  const all = await db.select().from(properties);
  console.log(`✅ Done! ${inserted} inserted, ${all.length} total in database.`);
}

main().catch(console.error);
